### ISSUE TITLE
Mining Hat Issue

### ISSUE THREAD

**Issue by Mikeliro** [cech12/UsefulHats#18]
The Mining Hat Night Vision enchantment time is very low, causing the sky to blink at night. You could increase the enchantment time and add something to the code that removes the enchantment when you stop holding the pickaxe.

**Comment by cech12** [comment]
Yeah, that is an issue! :) Thanks for it!

**Comment by Mikeliro** [comment]
My nephew has an epilepsy problem and this can be a trigger.

**Comment by cech12** [comment]
Fixed for all versions. The fix is included in the next update. ;)

**Comment by cech12** [comment]
released in 1.7.0
