### ISSUE TITLE
Tooltips off the screen

### ISSUE THREAD

**Issue by Zygus42** [cech12/UsefulHats#28]
![2020-09-11_12 23 30](https://user-images.githubusercontent.com/20757445/92859478-da358b00-f429-11ea-8b09-3410d22bf57a.png)

version: UsefulHats 1.8.1 - for Minecraft 1.16.1+

**Comment by cech12** [comment]
Thanks for reporting! It seems to be a problem with Forge. Is there any other mod with the same problem?

Which Forge version are you using?

**Comment by cech12** [comment]
Since Minecraft 1.16.2 this issue occurs. Forge removed a method (GuiUtils.drawHoveringText) which was used here. Wait for this PR https://github.com/MinecraftForge/MinecraftForge/pull/7268

**Comment by cech12** [comment]
Okay the PR only reimplemented the former GuiUtils.drawHoveringText method but not the call in the standard tooltip rendering...

**Comment by cech12** [comment]
fixed and released in mod version 1.8.4
