### ISSUE TITLE
Optifine?!

### ISSUE THREAD

**Issue by cech12** [cech12/UsefulHats#33]
Check if there are problems with Optifine installed. I saw several videos where the own hat model is not rendered. Maybe this has something to do with Optifine.

**Comment by cech12** [comment]
Nope, there is no general problem with Optifine.

**Comment by Aizistral** [comment]
Very thoughtful issue management.

By the way, it is possible that hat rendering can be disabled by players if they wear hats in Curios slots, since Curios itself provides such feature. You probably know already, but just in case.

**Comment by cech12** [comment]
hehe thanks ^^

Yes, disabling hat rendering is possible when worn in a curios slot :)
