### ISSUE TITLE
Hats that modify block break speed like mining hat or straw hat not working

### ISSUE THREAD

**Issue by Alec2092** [cech12/UsefulHats#38]
I saw this " https://github.com/cech12/UsefulHats/issues/22#issue-689375246 " but I dont have silent gear instaled, there is any way to solve this? Or at least a way to know which mod is causing the issue/known mods causing this?

**Comment by cech12** [comment]
Please send me some information about your installation:
Minecraft version, version of the mod, maybe a modpack (name & version), a log file
Without this information I cannot fix your issue.

Hint: The increase lies only at 20%. Maybe you don't notice a difference^^ 
You can test to enchant the hat with Efficiency 5.

**Comment by Alec2092** [comment]
Minecraft version: 1.16.4 |
Mod version: 1.9.3 |
Not a specific modpack but mods that are shown in the image: " https://imgur.com/a/2l5H7cn " |
Log file: " https://mega.nz/file/3fBgFbQJ#RjgTODf32nE4kbScCaf-3Spq4A7HogRKfIWZ_guI0xc "|


And I messed up with the settings a little bit just in case it was because I wasn't noticing (I put exaggerated values like a 200% [edit: in config] and so) Also I calculated the time mining with and whitout the helmet and it was the same so it's definitely that is not increasing speed and I believe it's because one of the mods but no idea which one :/


Also sorry if my english is really bad, I did my best to solve all typos and making everything readable

**Comment by cech12** [comment]
I cannot figure out which mod it could be. Did you test if it works without any other mod? ^^

Can you send me a log file of you modpack of the following situation:
- close minecraft 
- start minecraft
- generate a new creative world
- get an axe and the chopping hat from the creative inventory
- change to survival mode
- put the chopping hat on
- chop a wood block
- close minecraft
That log should be better to read. :D

The Forge version is 35.1.36 right?

**Comment by Alec2092** [comment]
**Finally got it working!**
 I did some things before sending the log like removing the mod "reap" that have a function like treecapitator (https://media2.giphy.com/media/XgXXSl45Zp9YyBq8x5/giphy.gif) and removing the configuration of this mod so it resets to default and somehow now works so its either the reap mod or the config file, also at least this time is not wasted because in the tests (to test if finally works) I noticed that the speed increase that the helmet says is not 100% accurate

For example in the tests I put it like this:

"miningHatSpeedWithEfficiency0 = 1.0"
And the mining helmet says 100% speed increase but I did 2 stone towers and without the helmet the time was around 39-40seconds while with the helmet that it's supposed to be 20 seconds because 100% increase it means double the speed but it's not because the time was 28-29 seconds

But anyways thanks for the help, because if you didn't answer in the first place I wouldn't have solved it so thanks you very much! I love your vanilla friendly mods, and thanks again!

**Comment by cech12** [comment]
There is a small amount of time between two block breaks which is constant (unreleated to the break time). 
This could cause this "inaccuracy".

You could compare the time of breaking only one block like obsidian. ;)

I opened a new ticket for checking the incompatibility with Reap Mod. Thanks for your tests and for sharing your findings :D
