### ISSUE TITLE
[1.16.5] Client Crash on boot up?

### ISSUE THREAD

**Issue by Yourname942** [cech12/UsefulHats#40]
Useful Hats (usefulhats) encountered an error during the sided_setup event phase 
    java.util.ConcurrentModificationException: null
    
**Environment:**
MC 1.16.5
Forge 36.1.2
UsefulHats 1.9.3-1.16.2+

**Steps to reproduce:**
1. boot up server
2. launch minecraft via curseforge app
3. minecraft app crashes with the following error (crashlog)

**Logs:**
crash log:
https://gist.github.com/Yourname942/ef1f74d3a84d35182c3e274ea6432675
latest log:
https://gist.github.com/Yourname942/a50806ddbef2dafb483419f2e6e1816a

**Comment by cech12** [comment]
Thanks for your report. I will look into this.

**Comment by cech12** [comment]
I cannot reproduce the described problem.
I installed MC Forge 1.16.5-36.1.2 in Curseforge App and added UsefulHats 1.9.3-1.16.2+. After starting the client, everything works fine.
Does the crash happens on server side or on client side?

You have multiple other mods installed. Is this a public modpack where I can test it?

**Comment by Yourname942** [comment]
This happens client side. It also does not happen every single time I boot up the server/client. Only sometimes, which makes it harder to reproduce. Yes it is, although the issue I am experiencing is with the current non-public build (where I updated mods and run tests to verify the stability of the server)

**Comment by cech12** [comment]
Super weird.^^ Startup crashes which only happen sometimes. xD
Which modpack is it? Then I can add my mod and check if there is a mod incompatibility. :)

**Comment by Yourname942** [comment]
The Land of Super Friends

**Comment by cech12** [comment]
Released the changes in version 1.16.4. I hope this fixes this issue. :)
