### ISSUE TITLE
[Bug]: Useful Hats mod drops my FPS straight to 2 or 4 FPS

### ISSUE THREAD

**Issue by Anselfx** [cech12/UsefulHats#61]
### Minecraft Version

1.21

### Mod Loader

Fabric

### Mod Loader Version

0.15.11-1.21

### Mod Version

6.0.2.0

### Modpack or other Mod

I haven't installed any modpack, just this one 

### Describe the Issue

When i use certains hats, for example the Mining, Chopping and Straw hats, it makes my FPS drop from 100 straight to 2 FPS 
(I'm using a NVIDIA RTX 3050 and a AMD Ryzen 7 5000 series)

### Do you use any performance-enhancing mods (e.g. OptiFine)?

I'm using Sodium

**Comment by cech12** [comment]
Thanks for your report! I will look into it when I have time :)

**Comment by Anselfx** [comment]
> Thanks for your report! I will look into it when I have time :)

That's great! Good luck

**Comment by cech12** [comment]
Smokey said on Discord:
Same issue on my end, Fabric 1.21
I think it has to do with the item tooltips
as even just hovering over in the inventory drops FPS from 300+ down to 20
Don't even need the item in my inventory
Also seems to only be certain hats since not everyone of them is doing it

**Comment by cech12** [comment]
Fixed in the upcoming release 1.21-6.1.0.0
Thanks again for your report! :D
