### ISSUE TITLE
[Bug]: Crash on startup with NeoForge 21.0.86

### ISSUE THREAD

**Issue by NielsPilgaard** [cech12/UsefulHats#64]
### Minecraft Version

1.21.0

### Mod Loader

NeoForge

### Mod Loader Version

21.0.86

### Mod Version

usefulhats-neoforge-1.21-6.2.0.0

### Modpack or other Mod

Enigmatica 10 dev

### Describe the Issue

I crash on startup when I have Useful Hats in my instance with recent NeoForge versions.

### Logs

https://gist.github.com/NielsPilgaard/3d26004754b74848b52075dfdaf77e65

### Do you use any performance-enhancing mods (e.g. OptiFine)?

ModernFix, Embeddium

**Comment by cech12** [comment]
Thanks for your report! Downgrading Neoforge to 21.0.81 could be a workaround for now until I fix that issue :)

**Comment by cech12** [comment]
Thanks again for your report! The crash is fixed in the upcoming version 1.21-6.3.0.0.

**Comment by NielsPilgaard** [comment]
Thank you 😊
